<a href="https://colab.research.google.com/github/Akshay-Rajesh/Note/blob/main/Naive_Bayes_ICTAK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("Social_Network_Ads.csv")

In [5]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [81]:
x = data.drop(["User ID","Gender"] , axis =1 )
y = data["Purchased"]

In [82]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size = 0.20, random_state =0)

In [83]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [84]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [85]:
y_pred = classifier.predict(x_test)

In [86]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
acc =accuracy_score(y_test,y_pred)

cm

array([[58,  0],
       [ 0, 22]])

In [88]:
print(acc)

1.0


In [89]:
from sklearn.naive_bayes import BernoulliNB
classi = BernoulliNB()
classi.fit(x_train,y_train)

BernoulliNB()

In [90]:
y_pred = classi.predict(x_test)

In [91]:
cm = confusion_matrix(y_test,y_pred)
acc =accuracy_score(y_test,y_pred)

In [92]:
cm

array([[58,  0],
       [ 0, 22]])

In [93]:
acc

1.0